"""
Zip Destination Handler
Creates downloadable .zip file with all generated documents
"""

import zipfile
import json
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any


class ZipHandler:
    """Create zip files with generated documentation"""
    
    def __init__(self, output_dir: str = "output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def create_zip(self, documents: List[Dict[str, Any]]) -> str:
        """
        Create a zip file with all documents
        
        Args:
            documents: List of generated documents with content and metadata
        
        Returns:
            Path to created zip file
        """
        
        # Create zip filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        zip_filename = f"docgen_{timestamp}.zip"
        zip_path = self.output_dir / zip_filename
        
        print(f"\n📦 Creating zip: {zip_filename}")
        
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
            
            # Add each document
            for i, doc in enumerate(documents, 1):
                # Add markdown document
                doc_name = doc['filename']
                zf.writestr(f"docs/{doc_name}", doc['content'])
                print(f"   ✓ Added: docs/{doc_name}")
                
                # Add metadata
                metadata_name = doc_name.replace('.md', '.json')
                zf.writestr(f"metadata/{metadata_name}", 
                           json.dumps(doc['metadata'], indent=2))
            
            # Add index.md
            index_content = self._generate_index(documents)
            zf.writestr("README.md", index_content)
            print(f"   ✓ Added: README.md")
            
            # Add manifest
            manifest = {
                'generated': datetime.now().isoformat(),
                'documents': len(documents),
                'files': [doc['filename'] for doc in documents],
                'quality_scores': [doc['metadata'].get('quality_score', 0) for doc in documents]
            }
            zf.writestr("manifest.json", json.dumps(manifest, indent=2))
            print(f"   ✓ Added: manifest.json")
        
        print(f"\n✅ Zip created: {zip_path}")
        return str(zip_path)
    
    def _generate_index(self, documents: List[Dict[str, Any]]) -> str:
        """Generate README.md index for zip contents"""
        
        lines = [
            "# Docgen Generated Documentation",
            "",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## Contents",
            ""
        ]
        
        for i, doc in enumerate(documents, 1):
            title = doc['metadata'].get('title', 'Document')
            category = doc['metadata'].get('category', 'Unknown')
            quality = doc['metadata'].get('quality_score', 0)
            filename = doc['filename']
            
            lines.append(f"{i}. **{title}** ({category})")
            lines.append(f"   - File: `docs/{filename}`")
            lines.append(f"   - Quality: {quality}/100")
            lines.append("")
        
        lines.extend([
            "## How to Use",
            "",
            "1. Extract this zip file",
            "2. Open `docs/` folder to view all markdown documents",
            "3. Check `metadata/` for detailed document metadata",
            "4. See `manifest.json` for complete file listing",
            "",
            "## Quality Gates",
            "",
            "All documents have passed 5-level quality gates:",
            "1. ✓ Validation (YAML, metadata)",
            "2. ✓ Structure (required sections)",
            "3. ✓ Content (clarity, examples)",
            "4. ✓ Metrics (token budget, quality score)",
            "5. ✓ Shipping (production-ready)",
            "",
            "---",
            "Generated by Docgen v1.0"
        ])
        
        return "\n".join(lines)
